version: '3.8'

services:
  mariadb-product:
    image: mariadb:11.2
    container_name: mariadb-product
    environment:
      MYSQL_ROOT_PASSWORD: loc2003
      MYSQL_DATABASE: microserviceDB
    ports:
      - "3307:3306" # tránh trùng cổng
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - backend

  mariadb-order:
    image: mariadb:11.2
    container_name: mariadb-order
    environment:
      MYSQL_ROOT_PASSWORD: loc2003
      MYSQL_DATABASE: orderdb
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - backend

  mariadb-customer:
    image: mariadb:11.2
    container_name: mariadb-customer
    environment:
      MYSQL_ROOT_PASSWORD: loc2003
      MYSQL_DATABASE: customerdb
    ports:
      - "3309:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - backend

networks:
  backend:
